source 'https://rubygems.org'
ruby ' >= 3.0.1'

gem 'sinatra'
gem 'pg'
gem 'rake'
gem 'sinatra-activerecord'
gem 'activesupport', '< 7'
gem 'activerecord', '< 7'
gem 'rack-attack'
gem 'redis-store'
gem 'telegram-bot-ruby'
gem 'puma'
