development:
  adapter: postgresql
  encoding: unicode
  database: mpz_feedback_development
  pool: 2
  username: app

production:
  adapter: postgresql
  encoding: unicode
  pool: 4
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
